# Generated by Django 4.2.20 on 2025-06-11 07:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('part_time', 'Part-time')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='join_date',
            field=models.DateField(auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('none', 'No Shift'), ('shift_1', '9:00 AM - 5:00 PM'), ('shift_2', '5:00 PM - 12:00 AM')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('salesman', 'Salesman'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
        migrations.CreateModel(
            name='PartTimeWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hours_worked', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(limit_choices_to={'employee_type': 'part_time'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
            ],
        ),
    ]
