# Generated by Django 4.2.20 on 2025-05-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_employee_remove_supplier_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='inventory_category',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='inventory_customer',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='inventory_employee',
        ),
        migrations.AlterModelTable(
            name='product',
            table='inventory_product',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='inventory_purchase',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='inventory_supplier',
        ),
    ]
