# Generated by Django 4.2.20 on 2025-06-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_employee_employee_type_employee_hourly_wage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity',
        ),
    ]
