# Generated by Django 4.2.20 on 2025-06-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_purchaseorder_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Arrived', 'Arrived')], default='Pending', max_length=20),
        ),
    ]
