# Generated by Django 4.2.20 on 2025-06-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_size',
            field=models.CharField(default='', help_text='e.g. 500 ml bottle', max_length=50),
        ),
    ]
