# Generated by Django 4.2.20 on 2025-06-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchaseorderdetail_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
