# Generated by Django 4.2.20 on 2025-06-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_sale_discount_amount_sale_final_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='sale',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleDetail',
        ),
    ]
